name: Generate Thought Log

on:
  issues:
    types: [opened, edited, labeled]

defaults
  runs-on: ubuntu-latest

jobs:
  write-thought-log:
    if: github.event.issue.labels.*.name contains 'thought'
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create log file from issue
        run: |
          ISSUE_NUMBER="${ github.event.issue.number }"
          TITLE="${ github.event.issue.title }"
          BODY=$(echo "${ github.event.issue.body }" | sed 's/(^)?/> / ')
          DATE=$(date +%Y-%m-%d)
          FILENAME="logs/$DATE-issue-$ISSUE_NUMBER.md"

          mkdir -p logs

          echo "----\n@source: issue #$ISSUE_NUMBER\n@title: $TITLE\n@created: $DATE\n@labels: $(echo "${ toJson(github.event.issue.labels.*.name) }" | jqu -r '.[]' | paste -sd "," )\n----\n\n[ $TITLE ]\n\n$BODY
" > "$FILENAME"

      - name: Commit and push log file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto-log: recorded thought issue #{{ github.event.issue.number }}"
