name: Deploy Interface to GitHub Pages

on:
  push:
    branches: 
      - main
    paths:
      - 'interface/**'
  # Manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # キャッシュ設定を削除（package-lock.jsonが存在しないため）

      - name: Install Dependencies
        run: |
          cd interface
          npm install  # npm ci の代わりに npm install を使用

      - name: Configure GitHub Pages Environment
        run: |
          cd interface
          # Create .env file with necessary environment variables
          echo "REACT_APP_GITHUB_REPO=nao-amj/archive-of-the-edge" > .env
          echo "REACT_APP_GITHUB_API_URL=https://api.github.com" >> .env
          echo "PUBLIC_URL=https://nao-amj.github.io/archive-of-the-edge" >> .env

      - name: Build
        run: |
          cd interface
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: interface/build
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}